### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to Chatty v2.18.1

### ISSUE THREAD

**Issue by SrBedrock** [Brikster/Chatty#61] opened 2020-06-19 17:31 UTC
```
[14:26:58 ERROR]: Could not pass event AsyncPlayerChatEvent to Chatty v2.18.1
ru.mrbrikster.chatty.util.gson.JsonSyntaxException: ru.mrbrikster.chatty.util.gson.stream.MalformedJsonException: Unterminated string at line 1 column 7832 path $.last-pm-interlocutor.IN_DANIBR
at ru.mrbrikster.chatty.util.gson.internal.Streams.parse(Streams.java:60) ~[?:?]
at ru.mrbrikster.chatty.util.gson.JsonParser.parse(JsonParser.java:84) ~[?:?]
at ru.mrbrikster.chatty.util.gson.JsonParser.parse(JsonParser.java:59) ~[?:?]
at ru.mrbrikster.chatty.util.gson.JsonParser.parse(JsonParser.java:45) ~[?:?]
at ru.mrbrikster.chatty.chat.JsonStorage.getProperty(JsonStorage.java:78) ~[?:?]
at ru.mrbrikster.chatty.chat.JsonStorage.getProperty(JsonStorage.java:106) ~[?:?]
at ru.mrbrikster.chatty.chat.Chat.lambda$getRecipients$1(Chat.java:65) ~[?:?]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1624) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
at ru.mrbrikster.chatty.chat.Chat.getRecipients(Chat.java:82) ~[?:?]
at ru.mrbrikster.chatty.chat.ChatListener.onChat(ChatListener.java:161) ~[?:?]
at ru.mrbrikster.chatty.chat.ChatListener.execute(ChatListener.java:95) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
at net.minecraft.server.v1_15_R1.PlayerConnection.chat(PlayerConnection.java:1785) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1700) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
at net.minecraft.server.v1_15_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: ru.mrbrikster.chatty.util.gson.stream.MalformedJsonException: Unterminated string at line 1 column 7832 path $.last-pm-interlocutor.IN_DANIBR
at ru.mrbrikster.chatty.util.gson.stream.JsonReader.syntaxError(JsonReader.java:1568) ~[?:?]
at ru.mrbrikster.chatty.util.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1031) ~[?:?]
at ru.mrbrikster.chatty.util.gson.stream.JsonReader.nextString(JsonReader.java:815) ~[?:?]
at ru.mrbrikster.chatty.util.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:702) ~[?:?]
at ru.mrbrikster.chatty.util.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723) ~[?:?]
at ru.mrbrikster.chatty.util.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723) ~[?:?]
at ru.mrbrikster.chatty.util.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698) ~[?:?]
at ru.mrbrikster.chatty.util.gson.internal.Streams.parse(Streams.java:48) ~[?:?]
... 27 more
```

**Comment by SrBedrock** [comment] 2020-06-19 20:18
```
[17:16:49 ERROR]: Could not pass event AsyncPlayerChatEvent to Chatty v2.18.1
java.lang.IllegalArgumentException: Cannot measure distance between world and world_nether
at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at ru.mrbrikster.chatty.chat.Chat.lambda$getRecipients$2(Chat.java:79) ~[?:?]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1624) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
at ru.mrbrikster.chatty.chat.Chat.getRecipients(Chat.java:82) ~[?:?]
at ru.mrbrikster.chatty.chat.ChatListener.onChat(ChatListener.java:161) ~[?:?]
at ru.mrbrikster.chatty.chat.ChatListener.execute(ChatListener.java:95) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.PlayerConnection.chat(PlayerConnection.java:1786) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1701) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at net.minecraft.server.v1_15_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.15.2.jar:git-Tuinity-"12efad6"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by SrBedrock** [comment] 2020-06-19 21:31
```
[18:28:16 ERROR]: Could not pass event AsyncPlayerChatEvent to Chatty v2.18.1
ru.mrbrikster.chatty.util.gson.JsonSyntaxException: java.io.EOFException: End of input at line 1 column 11733 path $.chat._yBorutoz_
at ru.mrbrikster.chatty.util.gson.internal.Streams.parse(Streams.java:58) ~[?:?]
at ru.mrbrikster.chatty.util.gson.JsonParser.parse(JsonParser.java:84) ~[?:?]
at ru.mrbrikster.chatty.util.gson.JsonParser.parse(JsonParser.java:59) ~[?:?]
at ru.mrbrikster.chatty.util.gson.JsonParser.parse(JsonParser.java:45) ~[?:?]
at ru.mrbrikster.chatty.chat.JsonStorage.getProperty(JsonStorage.java:78) ~[?:?]
at ru.mrbrikster.chatty.chat.JsonStorage.getProperty(JsonStorage.java:106) ~[?:?]
at ru.mrbrikster.chatty.chat.Chat.lambda$getRecipients$1(Chat.java:65) ~[?:?]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1624) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
at ru.mrbrikster.chatty.chat.Chat.getRecipients(Chat.java:82) ~[?:?]
at ru.mrbrikster.chatty.chat.ChatListener.onChat(ChatListener.java:161) ~[?:?]
at ru.mrbrikster.chatty.chat.ChatListener.execute(ChatListener.java:95) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
at net.minecraft.server.v1_15_R1.PlayerConnection.chat(PlayerConnection.java:1785) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1700) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
at net.minecraft.server.v1_15_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.io.EOFException: End of input at line 1 column 11733 path $.chat._yBorutoz_
at ru.mrbrikster.chatty.util.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1401) ~[?:?]
at ru.mrbrikster.chatty.util.gson.stream.JsonReader.doPeek(JsonReader.java:482) ~[?:?]
at ru.mrbrikster.chatty.util.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[?:?]
at ru.mrbrikster.chatty.util.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:722) ~[?:?]
at ru.mrbrikster.chatty.util.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723) ~[?:?]
at ru.mrbrikster.chatty.util.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698) ~[?:?]
at ru.mrbrikster.chatty.util.gson.internal.Streams.parse(Streams.java:48) ~[?:?]
... 27 more
```

**Comment by SrBedrock** [comment] 2020-06-19 21:32
Always happens with players who have _ in the nick

**Comment by Homosanians** [comment] 2020-06-27 15:09
Got the same trouble with Chatty v2.18 on Paper 1.16.1

```
>.... [15:06:07 ERROR]: java.lang.NullPointerException
>.... [15:06:07 ERROR]: java.lang.NullPointerException
>.... [15:06:07 WARN]: java.lang.NullPointerException
>.... [15:06:07 ERROR]: java.lang.NullPointerException
>.... [15:06:07 WARN]: java.lang.NullPointerException
>.... [15:06:07 WARN]: java.lang.NullPointerException
>.... [15:06:10 ERROR]: java.lang.NullPointerException
>.... [15:06:10 WARN]: java.lang.NullPointerException
>.... [15:06:10 ERROR]: java.lang.NullPointerException
>.... [15:06:10 WARN]: java.lang.NullPointerException
>.... [15:06:10 ERROR]: java.lang.NullPointerException
>.... [15:06:10 WARN]: java.lang.NullPointerException
>.... [15:06:12 ERROR]: java.lang.NullPointerException
>.... [15:06:12 ERROR]: java.lang.NullPointerException
>.... [15:06:12 WARN]: java.lang.NullPointerException
>.... [15:06:12 WARN]: java.lang.NullPointerException
>.... [15:06:12 ERROR]: java.lang.NullPointerException
>.... [15:06:12 WARN]: java.lang.NullPointerException
>.... [15:06:13 ERROR]: Could not pass event AsyncPlayerChatEvent to Chatty v2.18
java.util.regex.PatternSyntaxException: Illegal character range near index 10
[-a-zA-Zа-¤ј-я0-9@:%_\+.~#?&//=]{2,256}\.[a-z]{2,4}\b(\/[-a-zA-Zа-¤ј-я0-9@:%_\+~#?&//=]*)?
at java.util.regex.Pattern.error(Pattern.java:1969) ~[?:1.8.0_242]
at java.util.regex.Pattern.range(Pattern.java:2669) ~[?:1.8.0_242]
at java.util.regex.Pattern.clazz(Pattern.java:2576) ~[?:1.8.0_242]
at java.util.regex.Pattern.sequence(Pattern.java:2077) ~[?:1.8.0_242]
at java.util.regex.Pattern.expr(Pattern.java:2010) ~[?:1.8.0_242]
at java.util.regex.Pattern.compile(Pattern.java:1702) ~[?:1.8.0_242]
at java.util.regex.Pattern.<init>(Pattern.java:1352) ~[?:1.8.0_242]
at java.util.regex.Pattern.compile(Pattern.java:1028) ~[?:1.8.0_242]
at ru.mrbrikster.chatty.moderation.AdvertisementModerationMethod.<init>(AdvertisementModerationMethod.java:29) ~[?:?]
at ru.mrbrikster.chatty.moderation.ModerationManager.getAdvertisementMethod(ModerationManager.java:51) ~[?:?]
at ru.mrbrikster.chatty.chat.ChatListener.onChat(ChatListener.java:235) ~[?:?]
at ru.mrbrikster.chatty.chat.ChatListener.execute(ChatListener.java:95) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.1.jar:git-Paper-"d82de98"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-"d82de98"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-"d82de98"]
at net.minecraft.server.v1_16_R1.PlayerConnection.chat(PlayerConnection.java:1820) ~[patched_1.16.1.jar:git-Paper-"d82de98"]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1735) ~[patched_1.16.1.jar:git-Paper-"d82de98"]
at net.minecraft.server.v1_16_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.1.jar:git-Paper-"d82de98"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_242]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by Homosanians** [comment] 2020-06-27 15:45
@SrBedrock Probably you transferred something from the old config to the new one. If the problem is persistent, exclude that the problem is related to the config

**Comment by Brikster** [comment] 2021-07-21 19:43
Должно быть пофикшено в актуальных версиях.

**Closed by Brikster** 2021-07-21 19:43 UTC
Labels: bug

**Comment by saYDEX93** [comment] 2024-12-16 15:10
2.19.2 не фикшено.

**Comment by saYDEX93** [comment] 2024-12-16 15:10
[18:07:24 ERROR]: Could not pass event AsyncPlayerChatEvent to Chatty v2.19.2
ru.mrbrikster.chatty.shaded.gson.JsonSyntaxException: ru.mrbrikster.chatty.shaded.gson.stream.MalformedJsonException: Unterminated string at line 1 column 142272 path $.last-pm-interlocutor.SigmaHelBoze
        at ru.mrbrikster.chatty.shaded.gson.internal.Streams.parse(Streams.java:60) ~[?:?]
        at ru.mrbrikster.chatty.shaded.gson.JsonParser.parse(JsonParser.java:84) ~[?:?]
        at ru.mrbrikster.chatty.shaded.gson.JsonParser.parse(JsonParser.java:59) ~[?:?]
        at ru.mrbrikster.chatty.shaded.gson.JsonParser.parse(JsonParser.java:45) ~[?:?]
        at ru.mrbrikster.chatty.chat.JsonStorage.getProperty(JsonStorage.java:81) ~[?:?]
        at ru.mrbrikster.chatty.chat.JsonStorage.getProperty(JsonStorage.java:109) ~[?:?]
        at ru.mrbrikster.chatty.dependencies.PlayerTagManager.getPrefix(PlayerTagManager.java:23) ~[?:?]
        at ru.mrbrikster.chatty.chat.ChatListener.onChat(ChatListener.java:138) ~[?:?]
        at ru.mrbrikster.chatty.chat.ChatListener.execute(ChatListener.java:95) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:225) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:107) ~[patched_1.16.5.jar:git-Purpur-1171]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:65) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:2232) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2147) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2085) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:43) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: ru.mrbrikster.chatty.shaded.gson.stream.MalformedJsonException: Unterminated string at line 1 column 142272 path $.last-pm-interlocutor.SigmaHelBoze
        at ru.mrbrikster.chatty.shaded.gson.stream.JsonReader.syntaxError(JsonReader.java:1568) ~[?:?]
        at ru.mrbrikster.chatty.shaded.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1031) ~[?:?]
        at ru.mrbrikster.chatty.shaded.gson.stream.JsonReader.nextString(JsonReader.java:815) ~[?:?]
        at ru.mrbrikster.chatty.shaded.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:702) ~[?:?]
        at ru.mrbrikster.chatty.shaded.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723) ~[?:?]
        at ru.mrbrikster.chatty.shaded.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:723) ~[?:?]
        at ru.mrbrikster.chatty.shaded.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698) ~[?:?]
        at ru.mrbrikster.chatty.shaded.gson.internal.Streams.parse(Streams.java:48) ~[?:?]
        ... 23 more

**Comment by saYDEX93** [comment] 2024-12-16 15:11
![image](https://github.com/user-attachments/assets/a5c6faf4-ac5b-482e-af07-b38db29e4185)
